project:
  type: website

website:
  title: "378FinalNew"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: eda.qmd
        text: EDA
      - href: model.qmd
        text: Model

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

